# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [27]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [28]:
A = np.arange(1, 16).reshape(3,5)

In [29]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)
print(type(A))

2
(3, 5)
15
int32
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [30]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [31]:
print(B - C)

print(B * C)

print(B @ C)
# print(B.dot(C))

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [32]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(np.exp(B))

print(np.min(B))

print(B.min(axis=1))

print(B.min(axis=0))

print(np.argmin(B))

print(np.argmin(B, axis=1))
print(np.argmax(B, axis=0)) #index value for max value for each column

print(np.sum(B))

print(np.mean(B, axis=0))

print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
[2 2 2]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [34]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [37]:
print(A[1])
print(A[1,:])

[ 6  7  8  9 10]
[ 6  7  8  9 10]


**Answer:**

From numpy.org: "Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas.
When fewer indices are provided than the number of axes, the missing indices are considered complete slices."

Det betyder att A[1, :] == A[1]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [27]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [29]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [10]:
a = np.arange(30)
b = a.reshape((2, 3, -1)) #(subarrays, rows, columns)
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [44]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [49]:
a = x.reshape(-1, 3)
b = x.reshape(3, -1)
print(a)
print(b)

# c = x.reshape(-1, -1)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


Code creates an array ranging from 0 to 30 (a). This array is reshaped into 2 matrixes each with 3x5. -1 is set for automatically sized matrixes. b has three axes. The number of axes correspond to the number of dimensions to describe the array. Here, there are 2 axes to describe each row (axis 0 and 1) and axis 2 is the number of matrixes.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [31]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [32]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [33]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [39]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [40]:
def add_mult_matrices(arg1,arg2,arg3):
    """calculator for adding (actually, subtracting) and multiplying two matrixes"""
    if isinstance(arg1, np.ndarray) == isinstance(arg2, np.ndarray):
        if arg3 == "add":
            if arg1.shape == arg2.shape:
                return arg1-arg2
            else:
                print("Matrixes shapes does not match for add")
#                 pass # pass låter gå över till nästa operation
        elif arg3 == "multiply":
            if arg1.shape[1] == arg2.shape[0]:
                return arg1 @ arg2
            else:
                print("Matrixes shapes does not match for multiply")
#                 pass
#         else:
#             pass

In [41]:
print(add_mult_matrices(B,2*A,"add"))
print(add_mult_matrices(3*C,E,"add"))
print(add_mult_matrices(A,C,"multiply"))
print(add_mult_matrices(C,D,"multiply"))
print(add_mult_matrices(C,B,"multiply"))

[[ 0 -4  3]
 [ 0 -2 -4]]
Matrixes shapes does not match for add
None
Matrixes shapes does not match for multiply
None
[[11 10]
 [10 11]]
[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [39]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print(add_mult_matrices(A,B,"multiply"))
print(add_mult_matrices(A,C,"multiply"))

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]


**Chap2. Question 3**

In [20]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])
AD = add_mult_matrices(A,D,"multiply")
DA = add_mult_matrices(D,A,"multiply")

print((AD == DA).all())

False


**Quiz p.11, Question 2**

In [41]:
#Question 1
# a = np.array([[1, 0], [0, -1]])
# b = np.array([[-1, 0], [0, 1]])
# c = np.array([[0, 1], [-1, 0]])
# d = np.array([[0, -1], [1, 0]])

# matrix_list = [a, b, c, d]
# index_matrix = np.array([[1-1, 1-2], [2-1, 2-2]])

# for matrix in matrix_list:
#     print(add_mult_matrices(matrix,index_matrix,"add"))
        

In [42]:
#Question 2
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

add_mult_matrices(A,B,"multiply")

array([[-2,  2],
       [ 2, -2]])

**Chap 6. Question 1**

In [23]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])
print(np.linalg.inv(A))
print(np.linalg.inv(B))

#Verifiering av t ex B:
print((np.allclose(np.linalg.inv(B)@B, np.eye(2))))

[[ 5. -6.]
 [-4.  5.]]
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]
True


**Quiz p.19, Question 3**

In [44]:
#Quiz p.15, Q3
A = np.array([[2, 2], [1, 2]])

print(2*np.linalg.inv(A))

[[ 2. -2.]
 [-1.  2.]]


In [45]:
#Quiz p.22, Q3
a = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])
b = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
c = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
d = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])

count=1
matrix_list = [a, b, c, d]
for matrix in matrix_list:
    current_matrix = matrix
    print(count)
    for matrix in matrix_list:
        print(current_matrix)
        print(add_mult_matrices(current_matrix,matrix,"multiply"))
        print()
    count += 1


1
[[0 1 0]
 [0 0 1]
 [1 0 0]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]

[[0 1 0]
 [0 0 1]
 [1 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[0 1 0]
 [0 0 1]
 [1 0 0]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[0 1 0]
 [0 0 1]
 [1 0 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]

2
[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[0 1 0]
 [0 0 1]
 [1 0 0]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[1 0 0]
 [0 0 1]
 [0 1 0]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]

3
[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[1 0 0]
 [0 0 1]
 [0 1 0]]

[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[0 1 0]
 [0 0 1]
 [1 0 0]]

4
[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]

[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]

[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]



**Chap10. Question 1 a)**

In [46]:
a = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([[-7], [5], [2]])

np.linalg.solve(a, b)

array([[ 3.],
       [ 4.],
       [-6.]])

**Chap10. Question 1 b)**

In [47]:
a = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([[1], [-1], [1]])

np.linalg.solve(a, b)

array([[ 8.],
       [ 2.],
       [-1.]])

**Chap 12. Question 1**

In [48]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

np.linalg.inv(A)

array([[ 0.66666667,  1.33333333,  0.5       ],
       [ 1.        ,  2.        ,  0.5       ],
       [-3.        , -5.        , -1.        ]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [49]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [50]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [51]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
